[2024-09-19 16:54:51,370] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: task2_dag.python_task manual__2024-09-19T16:49:31.710862+00:00 [queued]>
[2024-09-19 16:54:51,373] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: task2_dag.python_task manual__2024-09-19T16:49:31.710862+00:00 [queued]>
[2024-09-19 16:54:51,373] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-09-19 16:54:51,373] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-09-19 16:54:51,373] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-09-19 16:54:51,377] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): python_task> on 2024-09-19 16:49:31.710862+00:00
[2024-09-19 16:54:51,380] {standard_task_runner.py:52} INFO - Started process 61469 to run task
[2024-09-19 16:54:51,381] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'task2_dag', 'python_task', 'manual__2024-09-19T16:49:31.710862+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/task2.py', '--cfg-path', '/var/folders/ks/w6y0t6b552bdg88w8kq5g_xc0000gn/T/tmpqjmtny_6', '--error-file', '/var/folders/ks/w6y0t6b552bdg88w8kq5g_xc0000gn/T/tmpkqg7byc3']
[2024-09-19 16:54:51,382] {standard_task_runner.py:80} INFO - Job 24: Subtask python_task
[2024-09-19 16:54:56,401] {task_command.py:371} INFO - Running <TaskInstance: task2_dag.python_task manual__2024-09-19T16:49:31.710862+00:00 [running]> on host MBPdeCharmaine
[2024-09-19 16:55:01,424] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=task2_dag
AIRFLOW_CTX_TASK_ID=python_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-19T16:49:31.710862+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-19T16:49:31.710862+00:00
[2024-09-19 16:55:01,424] {task2.py:31} INFO - Hello from Airflow
[2024-09-19 16:55:01,424] {python.py:173} INFO - Done. Returned value was: None
[2024-09-19 16:55:01,427] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=task2_dag, task_id=python_task, execution_date=20240919T164931, start_date=20240919T165451, end_date=20240919T165501
[2024-09-19 16:55:01,434] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-19 16:55:01,439] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
